version: '3.7'

services:
  web:
    image: nginx:1
    restart: unless-stopped
    ports:
      - 4200:80
    volumes:
      - "./../angular-app/dist/angular-app:/usr/share/nginx/html"
      - "./default.conf:/etc/nginx/conf.d/default.conf"

  kratos-migrate:
    image: oryd/kratos:v0.8.0-alpha.3-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  # kratos-selfservice-ui-node:
  #   image: oryd/kratos-selfservice-ui-node:v0.8.0-alpha.3
  #   ports:
  #     - "4455:4455"
  #   environment:
  #     - KRATOS_PUBLIC_URL=http://kratos:4433/
  #     - PORT=4455
  #     - SECURITY_MODE=
  #     - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
  #   networks:
  #     - intranet
  #   restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.8.0-alpha.3-sqlite
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

networks:
  intranet:

volumes:
  kratos-sqlite: